# .github/workflows/deploy.yml
# IMPORTANTE: 
# pendiente de configurar el deploy a AWS, por ahora solo se ejecuta el build para verificar que no haya errores en el proceso de construcción del proyecto.
name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci
      - run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Deploy (placeholder)
        run: echo "Deploy your service here"

      - name: Run DB migrations
        run: npx prisma migrate deploy